FROM golang

ADD . /go/src/chit_chat
WORKDIR /home/catcatproer/data/demo/go_web/src/chit_chat
RUN cd /
RUN ls
# RUN go get github.com/lib/pg
# RUN go install /go/src/chit_chat

# ENTRYPOINT /go/bin/chit_chat

EXPOSE 8080